### ISSUE TITLE
Doesnt work - Locale parameter removed after starting

### ISSUE THREAD

**Issue by Knives3** [austinyen56/League-of-Legends-Language-Changer#7]
Hi! I've wanted to try use your bat script because the shortcut method of changing the language stopped working for me, but it seems that this method doesnt work for me either. When the shortcut is created and not opened, it has the locale parameter that I selected in the command prompt. After I open the shortcut, the parameter is removed and the client opens in the default language (in my case english). Could you take a look into that please?

![grafik](https://github.com/austinyen56/League-of-Legends-Language-Changer/assets/93972231/2058e7aa-5a60-4b57-894a-e50215846bae) (After it has been opened)

![grafik](https://github.com/austinyen56/League-of-Legends-Language-Changer/assets/93972231/f6d5a202-178d-4a87-8d35-829a29bb8da7) (Before it has been opened)

**Comment by austinyen56** [comment]
>  the shortcut method of changing the language stopped working for me

Did it work for you in the past? This bat script is basically automating the shortcut method so you don't have to manually create a shortcut and type in locale

> After I open the shortcut, the parameter is removed

Thats normal behavior, it occurs on my end too because we are force setting the region on that instance

What is the directory path you set? Is it the default path?
Also is there an existing icon on your desktop? Maybe try removing it and run the script again?

**Comment by Knives3** [comment]
Thank you for your quick response. The problem was indeed that there were shortcuts already on my desktop, so after deleting those, my league client was in the language I chose.

**Comment by austinyen56** [comment]
Awesome! Glad to hear that it is resolved :)
